CIS_264_Price_APP/Models/Misc/Misc_G_L.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CIS_264_Price_APP.Models.Misc
{
    public class Misc_G_L
    {
        [Key]
        public int Misc_G_L_ID { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }

        public string Details { get; set; }
        public virtual Miscellaneous Miscellaneous { get; set; }
    }
}

CIS_264_Price_APP/Controllers/MiscellaneousControllers/Misc_G_LController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CIS_264_Price_APP.Data;
using CIS_264_Price_APP.Models.Misc;

namespace CIS_264_Price_APP.Controllers.MiscellaneousControllers
{
    public class Misc_G_LController : Controller
    {
        private CIS_264_Price_APPContext db = new CIS_264_Price_APPContext();

        // GET: Misc_G_L
        public ActionResult Index()
        {
            return View(db.Misc_G_L.ToList());
        }

        // GET: Misc_G_L/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Misc_G_L misc_G_L = db.Misc_G_L.Find(id);
            if (misc_G_L == null)
            {
                return HttpNotFound();
            }
            return View(misc_G_L);
        }

        // GET: Misc_G_L/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Misc_G_L/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Misc_G_L_ID,Category,Name,Price,Details")] Misc_G_L misc_G_L)
        {
            if (ModelState.IsValid)
            {
                db.Misc_G_L.Add(misc_G_L);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(misc_G_L);
        }

        // GET: Misc_G_L/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Misc_G_L misc_G_L = db.Misc_G_L.Find(id);
            if (misc_G_L == null)
            {
                return HttpNotFound();
            }
            return View(misc_G_L);
        }

        // POST: Misc_G_L/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Misc_G_L_ID,Category,Name,Price,Details")] Misc_G_L misc_G_L)
        {
            if (ModelState.IsValid)
            {
                db.Entry(misc_G_L).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(misc_G_L);
        }

        // GET: Misc_G_L/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Misc_G_L misc_G_L = db.Misc_G_L.Find(id);
            if (misc_G_L == null)
            {
                return HttpNotFound();
            }
            return View(misc_G_L);
        }

        // POST: Misc_G_L/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Misc_G_L misc_G_L = db.Misc_G_L.Find(id);
            db.Misc_G_L.Remove(misc_G_L);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CIS_264_Price_APP/Views/Misc_G_L/Create.cshtml
@model CIS_264_Price_APP.Models.Misc.Misc_G_L

<!DOCTYPE html>
<!-- 10/03/2021 -->
<html lang="en">
<head>

    <meta charset="utf-8">
    <link href="~/Styles/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="TBD(L)">

</head>
<body>

    <div id="wrapper">
        <h1>Misc.</h1>
        <h1>G - L</h1>
        <div id="content">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="formbox">
                <h4>Create</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <!--<div class="form-group">-->

                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="form-group">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="form-group">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="form-group">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control " } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

                <div class="form-group ">

                    <input type="submit" value="Create" class="btn btn-default" />

                </div>
                <!--</div>-->
            }

        </div>
    </div>
    <br />
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

CIS_264_Price_APP/Views/Misc_G_L/Delete.cshtml
@model CIS_264_Price_APP.Models.Misc.Misc_G_L

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title> Arts/Crafts </title>
    <meta charset="utf-8">
    <link href="~/Styles/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="TBD(L)">

</head>
<body>

    <div id="wrapper">
        <h2>Delete</h2>
        <div id="content">
            <h3>Are you sure you want to delete this?</h3>
            <div>


                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Category): @Html.DisplayFor(model => model.Category)
                    </dt>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
                    </dt>

                    <dt>
                        @Html.DisplayNameFor(model => model.Price): @Html.DisplayFor(model => model.Price)
                    </dt>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" />

                    </div>
                }
            </div>
        </div>
    </div>
    <br />
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

CIS_264_Price_APP/Views/Misc_G_L/Edit.cshtml
@model CIS_264_Price_APP.Models.Misc.Misc_G_L

@{
    Layout = null;
}

<!DOCTYPE html>
<!-- 10/03/2021 -->
<html lang="en">
<head>

    <meta charset="utf-8">
    <link href="~/Styles/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="TBD(L)">

</head>
<body>

    <div id="wrapper">
        <h1>Misc.</h1>
        <h1>G - L</h1>
        <div id="content">


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Misc_G_L_ID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            }

        </div>
    </div>
    <br />
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

CIS_264_Price_APP/Views/Misc_G_L/Index.cshtml
@model IEnumerable<CIS_264_Price_APP.Models.Misc.Misc_G_L>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>

<head>
    <title>  Misc. </title>
    <meta charset="utf-8">
    <link href="~/Styles/StyleSheet1.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="TBD(L)">

</head>

<body>

    <div id="wrapper">
        <h1> Misc.</h1>
        <h1>G - L</h1>
        <div id="content">
            <p>
                <button class="protected disable" id="miscCreate" type="button" onclick="location.href='@Url.Action("Create", "Misc_G_L" )'">Create</button>
            </p>
            <table class="table miscLight">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Category)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    
                </tr>

                @foreach (var item in Model.OrderBy(x => x.Category))
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <button class="detailsBtn">Details</button>
                    <p class="detail disable">@Html.DisplayFor(modelItem => item.Details) </p>
                </td>
                <td class="protected disable" width="15%">
                    <button class="protected disable" id="miscEdit" type="button" onclick="location.href='@Url.Action("Edit", "Misc_G_L", new { id = item.Misc_G_L_ID } )'">Edit</button>
                    <button class="protected disable" id="miscDel" type="button" onclick="location.href='@Url.Action("Delete", "Misc_G_L", new { id = item.Misc_G_L_ID } )'">Delete</button>
                </td>
            </tr>
                }

            </table>

        </div>
    </div>
    <br />
    <div>
        <button class="misc" id="misc" type="button" onclick="location.href='@Url.Action("Index", "Miscellaneous" )'">Back to list</button>
    </div>
</body>
</html>